# Generated by Django 5.2.8 on 2026-05-02 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0038_student_level_of_study_alter_staffprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('HEALTH_MANAGER', 'Health Manager'), ('MAINTENANCE_SUPERVISOR', 'Maintenance Supervisor'), ('WARDEN', 'Warden'), ('FINANCE_OFFICER', 'Finance Officer'), ('SECURITY_OFFICER', 'Security Officer'), ('NEWS_EDITOR', 'News Editor'), ('AUDITOR', 'Auditor'), ('EMERGENCY_COORDINATOR', 'Emergency Coordinator'), ('SUPPORT_AGENT', 'Support Agent'), ('TVET_DIRECTOR', 'Diploma Coordinator (TVET)'), ('HOSTEL_MANAGER', 'Hostel Manager'), ('KITCHEN_MANAGER', 'Kitchen Manager'), ('DEAN_STUDENTS', 'Dean of Students')], max_length=50),
        ),
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.IntegerField(default=1)),
                ('used_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
