# Generated by Django 5.2.8 on 2026-05-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0039_alter_staffprofile_role_staffinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profiles/'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('HEALTH_MANAGER', 'Health Manager'), ('MAINTENANCE_SUPERVISOR', 'Maintenance Supervisor'), ('WARDEN', 'Warden'), ('FINANCE_OFFICER', 'Finance Officer'), ('SECURITY_OFFICER', 'Security Officer'), ('NEWS_EDITOR', 'News Editor'), ('AUDITOR', 'Auditor'), ('EMERGENCY_COORDINATOR', 'Emergency Coordinator'), ('SUPPORT_AGENT', 'Support Agent'), ('TVET_DIRECTOR', 'Diploma Coordinator (TVET)'), ('TVET_COORDINATOR', 'TVET Coordinator'), ('HOSTEL_MANAGER', 'Hostel Manager'), ('KITCHEN_MANAGER', 'Kitchen Manager'), ('DEAN_STUDENTS', 'Dean of Students')], max_length=50),
        ),
    ]
