# Generated by Django 5.2.8 on 2026-05-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0040_staffprofile_is_approved_staffprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('HEALTH_MGR', 'Health Manager'), ('MAINT_SUP', 'Maintenance Supervisor'), ('WARDEN', 'Warden'), ('FINANCE', 'Finance Officer'), ('SECURITY', 'Security Officer'), ('NEWS_EDITOR', 'News Editor'), ('AUDITOR', 'Auditor'), ('EMERGENCY', 'Emergency Coordinator'), ('SUPPORT', 'Support Agent'), ('DIPLOMA', 'Diploma Coordinator'), ('DEAN_HHS', 'Dean of Students'), ('DEFERMENT', 'Deferment Officer'), ('DEPT_MCS', 'Dept MCS Coordinator'), ('DVC_ASA', 'DVC ASA')], max_length=50),
        ),
    ]
