# Generated by Django 5.2.8 on 2026-05-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0042_add_notification_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, help_text='Required for DEPT_COORD role', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('HEALTH_MGR', 'Health Manager'), ('MAINT_SUP', 'Maintenance Supervisor'), ('WARDEN', 'Warden'), ('FINANCE', 'Finance Officer'), ('SECURITY', 'Security Officer'), ('NEWS_EDITOR', 'News Editor'), ('AUDITOR', 'Auditor'), ('EMERGENCY', 'Emergency Coordinator'), ('SUPPORT', 'Support Agent'), ('DIPLOMA', 'Diploma Coordinator'), ('DEAN_HHS', 'Dean of Students'), ('DEFERMENT', 'Deferment Officer'), ('DEPT_MCS', 'Dept MCS Coordinator'), ('DEPT_COORD', 'Department Coordinator'), ('VC', 'Vice Chancellor'), ('DVC', 'Deputy Vice Chancellor'), ('REG_ADMIN', 'Register Admin'), ('REG_USER', 'Register User'), ('DEAN_GRAD', 'Dean - Graduate School'), ('DIR_RESOURCE', 'Director - Resource Mobilization'), ('DIR_TVET', 'Director - TVET'), ('NEWS_AUDITOR', 'News Auditor')], max_length=50),
        ),
    ]
