# Generated by Django 5.2.8 on 2026-05-31 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0042_add_notification_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_coordinator',
            field=models.ForeignKey(blank=True, help_text='Diploma coordinator assigned to this student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_diploma_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('vice_chancellor', 'Vice Chancellor'), ('deputy_vice_chancellor', 'Deputy Vice Chancellor'), ('register_admin', 'Register Admin'), ('register_user', 'Register User'), ('dean_of_students', 'Dean of Students'), ('dean_graduate_school', 'Dean - Graduate School'), ('director_resource', 'Director - Resource Mobilization'), ('director_tvet', 'Director - TVET'), ('deferment_officer', 'Deferment Officer'), ('dept_mcs', 'Dept MCS Coordinator'), ('health_manager', 'Health Manager'), ('maintenance_sup', 'Maintenance Supervisor'), ('warden', 'Warden'), ('finance_officer', 'Finance Officer'), ('security_officer', 'Security Officer'), ('news_editor', 'News Editor'), ('news_auditor', 'News Auditor'), ('emergency_coord', 'Emergency Coordinator'), ('support_agent', 'Support Agent'), ('auditor', 'Auditor'), ('diploma_coordinator', 'Diploma Coordinator'), ('dept_coordinator', 'Department Coordinator')], max_length=50),
        ),
    ]
