# Generated by Django 5.2.8 on 2026-06-01 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0043_student_assigned_coordinator_alter_staffprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.permission')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
