# Generated by Django 5.2.8 on 2026-06-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0044_permission_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='access_type',
            field=models.CharField(choices=[('full', 'Full Access'), ('read', 'Read Only'), ('none', 'No Access')], default='full', max_length=20),
        ),
    ]
