# Generated by Django 5.2.8 on 2026-06-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0045_rolepermission_access_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The internal code name of the feature flag', max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Status of the feature flag')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
