# Generated by Django 5.2.8 on 2026-06-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0047_alter_staffprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsubscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='adminsubscription',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='pro', max_length=20),
        ),
        migrations.AddField(
            model_name='adminsubscription',
            name='student_count',
            field=models.IntegerField(default=1000),
        ),
    ]
