# Generated by Django 5.2.8 on 2026-06-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0051_student_academic_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_school',
            field=models.CharField(blank=True, choices=[('library', 'Library'), ('sasa', 'SASA – School of Arts and Social Sciences'), ('sed', 'SED – School of Education'), ('sob', 'SOB – School of Business'), ('shhs', 'SHHS – School of Health and Human Sciences'), ('sees', 'SEES – School of Environmental and Earth Sciences'), ('shss', 'SHSS – School of Humanities and Social Sciences'), ('spas', 'SPAS – School of Performing Arts and Sports'), ('diploma', 'Diploma'), ('finance', 'Finance'), ('dean', 'Dean of School')], help_text='Academic School', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_of_study',
            field=models.CharField(choices=[('diploma', 'Diploma'), ('bachelors', "Bachelor's"), ('masters', "Master's"), ('doctorate', 'Ph.D (Doctorate)'), ('postgrad_diploma', 'Postgrad Diploma'), ('certificate', 'Certificate')], default='bachelors', max_length=20),
        ),
    ]
